/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.1. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module halfAdder
    ( // Inputs
      input wire  a
    , input wire  b

      // Outputs
    , output wire  sum
    , output wire  carry
    );
  wire [1:0] result;

  assign result = {a ^ b,   a & b};

  assign sum = result[1:1];

  assign carry = result[0:0];


endmodule

